library(shiny)
library(RCurl)
library(RJSONIO)
library(jose)
library(dotenv)
load_dot_env('.env')


shinyServer(function(input, output, session) {
  
  auth0_tenant=Sys.getenv('AUTH0_TENANT')
  ## Load JWK (Json Web Key) from the auth0 tenant, replace <yourtenant> with your auth0 tenant.
  ## The JWK servers to validate JSON Web Tokens (JWT) generated by Auth0.
  jwk_auth0 =  fromJSON(getURL(paste0("https://",auth0_tenant,".auth0.com/.well-known/jwks.json")))$keys[[1]]
  jwk_key <- read_jwk(jwk_auth0)

  user <- reactive({
    req(input$accTok)
    ## This step will fail if the JWT is invalid, it's decrypting the JWT with the JWK.
    res = jwt_decode_sig(input$accTok, pubkey=jwk_key)
    res
  })

  output$userShow <- renderText({
    res = user()
    # Show all the properties of the JWT
    return(paste(names(unlist(res)), ": ", unlist(res), collapse='\n'))
  })

})
